### ISSUE TITLE
todo - 12.02.23

### ISSUE THREAD

**Issue by esocraton** [esocraton/react.js#11]
- [x] form projesi oluşturma ve bootstrap ekleme
- [x] formu sadeleştirme
- [x] form içindeki bilgilerin yeni task olarak eklenmesi
- [x] uuid ekleme ve öge silme (17 dk)
- [x] düzenle butonunun eklenmesi (6 dk)
- [x] task düzenleme aksiyonunun oluşturulması (7 dk)
- [x] ui düzenlemeleri ile yapının iyileştirilmesi (8 dk)
- [x] task filtreleme ve useEffect kullanımı (13 dk)
- [x] useEffect nedir? (3 dk)
- [x] içeriği yeni komponentle sadeleştirme (6 dk)
- [x] taskların localstorage içinde tutulması (14 dk)
