### ISSUE TITLE
todo - 01.01.23

### ISSUE THREAD

**Issue by esocraton** [esocraton/react.js#3]
- [x] Giriş
- [x] React Resmi Sayfası
- [x] Node ve VSCode Kurulumu
- [x] Terminalde Noktanın Kullanımı
- [x] create-react-app
- [x] React'ı Vite ile Kurmak ve Çalıştırmak
