### ISSUE TITLE
todo - 04.01.23

### ISSUE THREAD

**Issue by esocraton** [esocraton/react.js#6]
- [x] Props Drilling
- [x] Şartlı Rendering
- [x] Optionak Chain Kontrolü
- [x] useState Kullanımı
- [x] useState Örnek Kullanımı
- [x] useState ve Props ile Componentler Arası İletişim
