### ISSUE TITLE
todo - 08.01.23

### ISSUE THREAD

**Issue by esocraton** [esocraton/react.js#8]
- [x] Linkedin'de paylaşım nasıl yapılır?
- [x] Temel Matematiksel İşlemler
- [x] Değişken Atama ve Prompt
- [x] Şartlı İfadeler
- [x] Şartlı İfadeler 2
- [x] Fonksiyonlar
- [x] Özet Uygulama
- [x] Diziler
- [x] Dizilere Ait Fonksiyonlar
- [x] Nesnelerle Çalışmak
- [x] Örnek Uygulama
- [x] Döngüler
- [x] Örnek Uygulama
- [x] DOM Manipülasyonu
- [x] Google Anasayfasında DOM Manipülasyonu
- [x] getElementsByTagName
- [x] getElementByClassName
- [x] querySelector
- [x] getElementsByName
- [x] addEventListener
- [x] Node Eklemek
- [x] replaceChild
- [x] EcmaScript Nedir?
- [x] Scope-let-const
- [x] Fonksiyonlarda Yeni Özellik
- [x] İleri Dizi Fonksiyonları
- [x] Bazı Kritik Tespitler
- [x] Class
- [x] Proje
- [x] Proje Gönderimi
